apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

metadata:
  name: tekton-pipeline
  annotations:
    description: "Tekton Pipelines installation from latest release"
