apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "quizap.frontend.labels" . | nindent 4 }}
  {{- with (include "quizap.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "quizap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
