{{- if .Values.harbor.enabled }}
---
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: harbor-route
  namespace: {{ .Values.harbor.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: harbor-route
  body:
    # Set to 0 removes HTTP request body max size limits
    # Not recommended for production environments
    maxSize: "0"
{{- end }}